[poetry.style]
name = "style_poetry"
fontName = "Baskerville"
fontSize = "12"
leading = "16"
leftIndent = "60"
textColor = "#101010"

[poetry.settings]
newPageBefore = 0
newPageAfter = 0
newParagraphOnEndline = 1
blockSpaceBefore = "10"
blockSpaceAfter = "10"
